/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import TodoApp.controles.ProjectController;
import TodoApp.controles.TaksController;

import TodoApp.moldes.Project;
import TodoApp.moldes.Taks;
import java.util.Date;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        
//   teste para saber se esta tudo ok, entre salva as informações no banco de dados

//   ProjectController projectController =  new ProjectController();
        
//    Project project = new Project();
//    project.setName("projeto teste");
//    project.setDescription("Descrição");
//    projectController.save(project);
//    List<Project> projects = projectController.getall();
// dessa forma imprimo na tela a frase, total de projetos mais a quantidade
//    System.out.println("Total de projetos = " + projects.size());

// UPDATE DO PROJETO
// crio uma string do projeto para fazer a ligação do novo 

  ProjectController projectController =  new ProjectController(); 
    
   Project project = new Project();
// setando o valor do id para saber qual a tarefa para fazer o update
   project.setId(1);
   project.setName("nome novo do projeto");
   project.setDescription("Descrição do projeto");
   projectController.update(project);   
//  projectController.removeById();

    TaksController taksController = new TaksController ();
      
   Taks takss = new Taks ();
   takss.setIdproject(1);
   takss.setName("criar telas da aplicação");
  takss.setDescription("criar telas de cadastros");
  takss.setCpmpletada(Boolean.FALSE);
  takss.setNodes("sem notas");
  takss.setDeadline(new Date());
  
  taksController.update(takss);
      
    List<Taks> taks = taksController.getAll(1);
   System.out.print("total de tarefas = "+ taks.size());
     
   


        
       
    }

}
